// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Таблица хранения аккаунтов пользователей
type Account struct {
	// Уникальный идентификатор аккаунта
	ID pgtype.UUID
	// Адрес электронной почты пользователя
	Email string
	// Хэш пароля пользователя
	Password string
	// Дата и время создания аккаунта
	CreatedAt pgtype.Timestamp
	// Дата и время последнего обновления аккаунта
	UpdatedAt pgtype.Timestamp
	// Дата и время последней активности пользователя
	LastActivityAt pgtype.Timestamp
}
