// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             pgtype.UUID
	Email          string
	Password       string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	LastActivityAt pgtype.Timestamp
}
